### ISSUE TITLE
Final Update to Developer Guide

### ISSUE THREAD

**Issue by IsabelChong** [AY2223S2-CS2103T-T15-4/tp#220]
- [x] Initial updates to rename instances of `AB3` to `CLIpboard` (#221)
- [x] Update `Instructions for Manual Testing` (Part 1 #254 and Part 2 #255)
- [x] Update `Appendix for Effort` (#263 and #253)
- [x] Update `Planned Enhancements` (#265)
- [x] Rename existing diagrams of relevant instances of `AB3` to `CLIpboard` (#265)
- [x] Update the `Implementation` section
       - Add `undo`, `UniqueList` and `Storage - Serialized classes` implementation (#263)
       - Add UI implementation and navigations (#252)
       - Add object dependencies for `session` and `task` (#253)
       - Add UI components (#252)
       - Final update to diagrams (#277)
